[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "langchain-docqa"
version = "0.1.0"
description = "LangChain Document Q&A System"

[tool.hatch.build.targets.wheel]
packages = ["app"]

[flake8]
max-line-length = 100
